# Generated by Django 4.1.2 on 2023-02-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_address_register_data_remove_register_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='data',
        ),
    ]
